# Generated by Django 3.0.6 on 2020-05-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='ip',
            field=models.GenericIPAddressField(null=True, verbose_name='IP Address'),
        ),
    ]
